PIPELINE_NAME = "NetworkSecurity"
ARTIFACT_DIR = "Artifacts"

DATA_INGESTION_DIR_NAME = "data_ingestion"
DATA_INGESTION_FEATURE_STORE_DIR = "feature_store"
DATA_INGESTION_INGESTED_DIR = "ingested"

FILE_NAME = "data.csv"
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"

DATA_INGESTION_TRAIN_TEST_SPLIT_RATION = 0.2

# 🔥 CRITICAL — MUST MATCH MONGODB EXACTLY
DATA_INGESTION_DATABASE_NAME = "MUZAMIL"
DATA_INGESTION_COLLECTION_NAME = "NetworkData"